name: SFTP Deploy

on:
  push:
    branches:
      - main   # falls dein Branch anders heißt → ändern

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Upload auf SFTP Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: "./"
          remote_path: "/zielordner/"
